[workspace]
members = [ "docs/learning/computer_science/NeetCode150","docs/proof_of_concepts/dioxus/ssg","(projects)/luggage","(projects)/starcraft","(projects)/profiles/jimhillr","(projects)/sparkhill/website"]
resolver = "2"
