[target.x86_64-unknown-linux-gnu]
pre-build = [
    "apt-get update",
    "apt-get install -y libssl-dev pkg-config",
]

[target.x86_64-unknown-linux-musl]
pre-build = [
    "apk add openssl-dev openssl-libs-static pkgconf",
]
