[package]
name = "web"
version = "0.1.0"
edition = "2024"

[dependencies]
dioxus = { workspace = true, features = ["router"] }
ui = { workspace = true }
auth_sdk = { workspace = true }

[features]
default = ["web"]
web = ["dioxus/web"]
