[application]

[web.app]
# HTML title tag content
title = "Cahokia"

[web.watcher]

[web.resource]
# Additional CSS style files
style = []
# Additional JavaScript files
script = []

[web.resource.dev]
# JavaScript code file
# serve: [dev-server] only
script = []
