[package]
name = "pane"
version = "0.1.0"
edition = "2024"

[lints.clippy]
unwrap_used = "warn"
expect_used = "warn"

[lints.rust]
unsafe_code = "forbid"

[dependencies]
dioxus = { version = "0.7.2", features = ["web"] }

[features]
default = ["web"]
web = [] 
