[package]
name = "cast"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
chrono = "0.4.41"
clap = { version = "4", features = [ "derive" ]}
thiserror = "2.0.12"
uuid = { version = "1", features = [
    "v7",
] }

[dev-dependencies]
tempdir = "0.3.7"
