[workspace]
resolver = "2"
members = ["cloudflare", "web"]
default-members = ["web"]

[workspace.dependencies]
dioxus = { version = "0.7.2" }
auth_sdk = { path = "../auth_sdk" }

[profile]

[profile.wasm-dev]
inherits = "dev"
opt-level = 1

[profile.server-dev]
inherits = "dev"
