[workspace]
resolver = "2"
members = ["web"]

[workspace.dependencies]
dioxus = { version = "0.7.2" }

[profile]

[profile.wasm-dev]
inherits = "dev"
opt-level = 1

[profile.server-dev]
inherits = "dev"
